# Change these first
owner: thomaspj10 # Your GitHub organization or username, where this repository lives
repo: codifi-uptime-monitor # The name of this repository

sites:
  - name: Codifi marketing
    url: https://codifi.nl
  - name: Marktplaats
    url: https://marktplaats.codifi.nl
    headers:
      - "Authorization: Basic Upptime:$basic_auth_password"
  - name: Dashboard
    url: https://dashboard.codifi.nl
    headers:
      - "Authorization: Basic Upptime:$basic_auth_password"
  - name: Repository
    url: https://repository.codifi.nl
    headers:
      - "Authorization: Basic Upptime:$basic_auth_password"
  - name: Registry
    url: https://registry.codifi.nl
    headers:
      - "Authorization: Basic Upptime:$basic_auth_password"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /codifi-uptime-monitor
  name: Codifi
